
/* SenseVM Chibios hardware configuration and mapping file */
/* Should not be included into more than one C file (included in gpio.c per default) */

#ifndef SVM_CHIBIOS_CONF_H_
#define SVM_CHIBIOS_CONF_H_


#define LED0_GPIO GPIOD
#define LED0_PIN  13
#define LED0_MODE PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST

#define LED1_GPIO GPIOD
#define LED1_PIN  12
#define LED1_MODE PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST

#define BUTTON0_GPIO GPIOA
#define BUTTON0_PIN  0
#define BUTTON0_MODE PAL_MODE_INPUT
#define BUTTON0_EVENT_MODE PAL_EVENT_MODE_BOTH_EDGES

#define SYS_TIMER  5 /*select tim5 for system time*/


/* DEBUG */

#define DBG0_GPIO GPIOB
#define DBG0_PIN 3
#define DBG0_MODE PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST

#define DBG1_GPIO GPIOB
#define DBG1_PIN 4
#define DBG1_MODE PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST

#define DBG2_GPIO GPIOB
#define DBG2_PIN 5
#define DBG2_MODE PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST

#define DBG3_GPIO GPIOB
#define DBG3_PIN 6
#define DBG3_MODE PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST




#endif 
